.PHONY: build release test clean install manpage

TARGET_AARCH64 = aarch64-apple-darwin
TARGET_X86_64  = x86_64-apple-darwin

VERSION := $(shell cargo metadata --no-deps --format-version 1 \
	| python3 -c "import sys,json; print(json.load(sys.stdin)['packages'][0]['version'])")

build:
	cargo build

test:
	cargo test

manpage:
	cargo build
	@test -f target/man/swt.1 || (echo "ERROR: target/man/swt.1 not generated by build.rs" && exit 1)
	@echo "Man page at target/man/swt.1"

install: manpage
	cargo install --path .
	install -d /usr/local/share/man/man1
	install -m 644 target/man/swt.1 /usr/local/share/man/man1/swt.1
	@echo "Installed man page to /usr/local/share/man/man1/swt.1"

# Build a universal binary and create a release tarball (binary + man page).
release: manpage
	rustup target add $(TARGET_AARCH64)
	rustup target add $(TARGET_X86_64)
	cargo build --release --target $(TARGET_AARCH64)
	cargo build --release --target $(TARGET_X86_64)
	lipo -create \
		target/$(TARGET_AARCH64)/release/swt \
		target/$(TARGET_X86_64)/release/swt \
		-output target/swt-universal
	mkdir -p dist
	cp target/swt-universal dist/swt
	cp target/man/swt.1 dist/swt.1
	tar -czf dist/sparse-worktree-$(VERSION).tar.gz -C dist swt swt.1
	@echo "SHA256: $$(shasum -a 256 dist/sparse-worktree-$(VERSION).tar.gz | awk '{print $$1}')"
	@echo "Release tarball: dist/sparse-worktree-$(VERSION).tar.gz"

clean:
	cargo clean
	rm -rf dist
